import React, {ReactNode} from "react";
import Head from 'next/head';
import {LoginService} from "@/utils/login-service";
import dynamic from "next/dynamic";
import {Footer} from "flowbite-react";

interface ILayoutProps {
    children: ReactNode;
}

const isLoggedIn = LoginService.get().isLoggedIn();

const Nav = dynamic(() => import("@/components/layout/navigation/navBar"), {ssr: false});
const SignedInNav = dynamic(() => import("@/components/layout/navigation/signedInNavBar"), {ssr: false});

const Layout = ({children}: ILayoutProps) => {
    return (
        <>
            <Head>
                <title>Pesty Ninja</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            {isLoggedIn ? <SignedInNav></SignedInNav> : <Nav></Nav>}
            <div className="!min-h-[90vh]">
                {children}
            </div>

            {/*<Footer className="rounded-none">*/}
            {/*    <Footer.Copyright*/}
            {/*        href="/"*/}
            {/*        by="Ali Issa™"*/}
            {/*        year={2023}*/}
            {/*    />*/}
            {/*    <Footer.LinkGroup>*/}
            {/*        <Footer.Link href="/">*/}
            {/*            Index*/}
            {/*        </Footer.Link>*/}
            {/*    </Footer.LinkGroup>*/}
            {/*</Footer>*/}
        </>
    );
};

export default Layout;