import React, {ReactNode} from "react";
import NavBar from "./navigation/navBar";
import Head from 'next/head';

interface ILayoutProps {
    children: ReactNode;
}

const Layout = ({children}: ILayoutProps) => {
    return (
        <>
            <Head>
                <title>SoMe Frontend</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <NavBar/>
            <div className={"p-4 max-w-max"}>
                {children}
            </div>
        </>
    );
};

export default Layout;