import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>SoMe Frontend</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Titel</h1>
      </main>
    </>
  )
}
